- components/ui/button.tsx
- components/ui/navigation-menu.tsx
> change bg of buttons in navbar

- app/(pages)/(content)/anime/[slug]/components/actions/components/watch-stats.tsx
And also replace symbol of button to icon
> make watchButtons slightly bigger

- app/(pages)/components/footer.tsx
Додав посилання на фронтенд та бекенд, проте не знаю чи гарне місце для кнопки знайшов.
https://github.com/olexh/hikka-next/assets/53056080/a357f8e3-6ef1-4b7f-a5c4-acba45351354
> add github links

- app/(pages)/(root)/components/profile.tsx
You must have forgotten to fix or comment again :)
> fix(profile): add validation of episodes_total in handleAddEpisode

- app/(pages)/collections/new/components/collection-grid/collection-grid.tsx
- components/modals/search-modal/components/search-toggle.tsx
- components/modals/search-modal/components/ui/search-placeholders.tsx
- components/modals/search-modal/components/ui/user-card.tsx
- components/modals/search-modal/components/useSearchModal.ts
- components/modals/search-modal/components/useUserSearchList.ts
- components/modals/search-modal/components/user-search-list.tsx
- components/modals/search-modal/search-modal.tsx
- services/api/user/getUserList.tsx
- types/api.d.ts
Added a user search function and changed/added some files that were related to its implementation.
> Add User Search

- app/(pages)/(user)/u/[username]/components/collections/components/ui/collection-item.tsx
Я додав анімацію для тайтлу та опису, але забувся додати до постеру колекції
> fix(collection-modal): add blur transition to poster of collection

- app/(pages)/edit/components/edit-description/components/tags-modal.tsx
- app/(pages)/edit/components/edit-description/edit-description.tsx
[Screencast_20240521_004354.webm](https://github.com/hikka-io/hikka-next/assets/53056080/c8928d98-d206-48e3-b4d3-8774798d29cd)
> feat(edit-tags): add tags to existing text/tags

- services/hooks/watch/use-watch-list.ts
Added lines that are responsible for filtering by studios when requesting data
> BugFix: fixed a bug where the studio filter doesn't work

- features/anime/anime-view/followings/followings.component.tsx
> Add feature from trello/telegram

- components/manga-card.tsx
- components/novel-card.tsx
> Fix / Add Edit Button for Manga and Novel

- components/markdown/viewer/components/link.tsx
Потрбіно це все якось краще зробити, бо можна почати плакати від else if)
> feat: add link tooltip for manga, novel, person

- features/common/navbar/profile-menu.tsx
> Separators in Profile Menu and a little bit of sorting

- features/filters/prebuilt/age-rating.tsx
> fix: change name for age filter

- features/users/user-profile/user-favorites/anime.tsx
- features/users/user-profile/user-favorites/manga.tsx
- features/users/user-profile/user-favorites/novel.tsx
> feature: change content card in user favorites

- features/anime/anime-view/franchise.component.tsx
- features/manga/manga-view/franchise.component.tsx
- features/novel/novel-view/franchise.component.tsx
> feature: add sort to franchise

- components/markdown/viewer/plugins/remark-mentions.tsx
> feat(mention): add avatar to side of mention

- components/content-card/user-tooltip.tsx
- components/markdown/viewer/components/link.tsx
- features/common/navbar/profile-menu.tsx
- features/home/profile/profile.component.tsx
- features/modals/search-modal/search-toggle.tsx
- features/users/follow-button.component.tsx
- utils/constants.ts
also style(follow-button): change icons
https://github.com/hikka-io/hikka-next/assets/53056080/5cc61f79-a43f-4e5d-bde6-ad59633cfd39
> feat: user tooltip

- features/anime/anime-view/franchise.component.tsx
- features/manga/manga-view/franchise.component.tsx
- features/novel/novel-view/franchise.component.tsx
> fix: add more details for sorting franchise

- components/comments/global-comment.tsx
- types/api.d.ts
> add to homepage comments their source

- features/collections/collection-edit/collection-rules-alert.component.tsx
- features/collections/collection-edit/collection-title.component.tsx
> feat: add collection rules alert

- src/features/modals/search-modal/hooks/useAnimeSearchList.ts
- src/features/modals/search-modal/hooks/useCharacterSearchList.ts
- src/features/modals/search-modal/hooks/useMangaSearchList.ts
- src/features/modals/search-modal/hooks/useNovelSearchList.ts
- src/features/modals/search-modal/hooks/usePersonSearchList.ts
> fix: increased size values for queries in search

- src/components/ui/stack.tsx
- src/features/collections/collection-list/collection-item.tsx
- src/features/home/collections.component.tsx
> style(stack): improve blur content cards

- src/components/content-card/user-tooltip.tsx
> Style: added Markdown markup to user-tooltip

- src/utils/adapters/convert-notification.tsx
> Style: add bold tag for comment_tag

- src/components/content-card/user-tooltip.tsx
> Style: added alignment of statistic digits in user tooltip as in mockup

- src/features/anime/anime-view/links/links.component.tsx
> Style: remove outdate style for links in anime

- src/app/layout.tsx
https://github.com/user-attachments/assets/3e83121e-dd3e-4c23-89c6-97aba4c2426b
> style: add vaul-drawer-wrapper

- src/features/modals/search-modal/cards/anime-card.tsx
- src/features/modals/search-modal/cards/manga-card.tsx
- src/features/modals/search-modal/cards/novel-card.tsx
Before:
> ![image](https://github.com/user-attachments/assets/5cb3038e-8340-4e95-9aa2-799d24242fc6)
After:
> ![image](https://github.com/user-attachments/assets/77781641-3a87-42a5-835b-6b1ffcf3b9e4)
Trello: [link](https://trello.com/c/s54gPwjc/166-%D0%B2-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83-%D1%83-%D1%82%D0%B0%D0%B9%D1%82%D0%BB%D1%96%D0%B2-%D1%81%D1%82%D0%BE%D1%97%D1%82%D1%8C-%D1%8F%D0%BA%D1%89%D0%BE-%D0%BD%D0%B5%D0%BC%D0%B0%D1%94-%D0%B4%D0%B0%D1%82%D0%B8)
> Fix: Bug that showed a point in the search

- src/components/comments/global-comment.tsx
> fix(global-comment): fix icon size

- src/components/snowfall-manager.tsx
Також фіксить #91 (коміт фікса bf4bb27453dee7b79bd0d7c6364d4e3b920c7cd1)
https://github.com/user-attachments/assets/60be3c42-c309-4c28-abb8-fc3f9af3e015
https://github.com/user-attachments/assets/b31a014f-fb6a-485e-8088-9d4a6ce2535f
> add smooth disappear of snow & fix snowfall glitching

- src/components/ui/checkbox.tsx
- src/components/ui/select.tsx
> fix(select): fix checkbox align in select

- src/features/filters/collapsible-filter.tsx
- tailwind.config.js
https://github.com/user-attachments/assets/1c7cd13c-768c-4184-8c21-df69b4e85759
> Add animation on open and collapse of filter collapsible component 

- src/utils/constants/common.ts
https://t.me/hikka_io_chat/6/140332
> Style: update const for "Manhua"

- apps/web/src/components/ui/select.tsx
- apps/web/src/components/ui/tri-state-checkbox.tsx
- apps/web/src/features/filters/prebuilt/genre.tsx
https://github.com/user-attachments/assets/d3e8028f-c6d6-40ae-8d0c-dd02c3155ea0
> Genre Exclusion Filter

- apps/web/src/components/comments/comment.tsx
> Add User's Role in Comment
